// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using testTaskUzkikh.DbRepository;

#nullable disable

namespace testTaskUzkikh.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20220331105337_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("testTaskUzkikh.Models.UNP", b =>
                {
                    b.Property<long>("UnpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UnpId"), 1L, 1);

                    b.Property<int>("CKODSOST")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DLIKV")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DREG")
                        .HasColumnType("datetime2");

                    b.Property<long>("NMNS")
                        .HasColumnType("bigint");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("VKODS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VLIKV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VMNS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VNAIMK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VNAIMP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("VUNP")
                        .HasColumnType("bigint");

                    b.HasKey("UnpId");

                    b.HasIndex("UserId");

                    b.ToTable("Unps");
                });

            modelBuilder.Entity("testTaskUzkikh.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("testTaskUzkikh.Models.UNP", b =>
                {
                    b.HasOne("testTaskUzkikh.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
